/* main.c */
/* If you are using lit to compile, do not edit this file (platformer.c) directly as it will be overwritten in the main.lit compile process */
/* include_directives */
#include "raylib.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#if defined(__EMSCRIPTEN__)
	#include <emscripten/emscripten.h>
#endif

/* define_directives */


/* type_definitions */


/* external_variables */
const int screen_width = 800;
const int screen_height = 450;

/* function_prototypes */
void update_draw_frame(void);

int
main(void)
{
	SetConfigFlags(FLAG_VSYNC_HINT | FLAG_MSAA_4X_HINT | FLAG_WINDOW_HIGHDPI);
	InitWindow(screen_width, screen_height, "game");
	/* initialise_objects */
	

#if defined(__EMSCRIPTEN__)
	emscripten_set_main_loop(update_draw_frame, 0, 1);
#else
	SetTargetFPS(60);
	while (!WindowShouldClose())
	{
		update_draw_frame();
	}
#endif

	CloseWindow();
	return 0;
}

/* function_definitions */
void
update_draw_frame(void)
{
	/* update */
	

	
	/* opengl draw context */
	BeginDrawing();
	ClearBackground(RAYWHITE);
	/* draw */
	

	EndDrawing();
}



